services:
  gravatar:
    container_name: gravatar
    restart: unless-stopped
    build:
      context: .
    ports:
      - "${NGINX_PORT:-9999}:${NGINX_PORT:-9999}"
    volumes:
      - "${DATA_PATH}:${INTERNAL_DATA_PATH:-/data}:rw"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    env_file:
      - .env
